variables:
  project:  '$(Build.SourcesDirectory)\src\AzureSignTool\AzureSignTool.csproj'
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

trigger: 
  branches:
    include:
    - master

pr: none

steps:
- checkout: self
  
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 5.0.100
    installationPath: $(Agent.ToolsDirectory)\dotnet

- task: DotNetCoreCLI@2
  displayName: 'restore nuget'
  inputs:
    command: 'restore'
    projects: '$(project)'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '-c $(buildConfiguration) /p:Version=0.0.$(build.buildId)  /p:AllowUnsafeBlocks=True /p:LangVersion=latest'

- task: DotNetCoreCLI@2
  displayName: 'pack nuget'
  inputs:
    command: 'pack'
    configuration: '$(buildConfiguration)'
    packagesToPack: '$(project)'
    versioningScheme: 'off'
    buildProperties: 'Version="0.0.$(build.buildId)";AllowUnsafeBlocks="True";LangVersion="latest"'


- task: CmdLine@2
  displayName: 'list electronProject build'
  inputs:
    script: 'ls -hR $(Build.ArtifactStagingDirectory)'


- task: NuGetCommand@2
  displayName: 'push nuget'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)\AzureSign.0.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'